language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install codecov

# command to run tests
script: nosetests --with-coverage tests/

# create codecov report
after_success:
  - codecov